#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("HelloMoon.Resource", IsApplication=true)]

namespace HelloMoon
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int armstrong_on_moon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_launcher = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int fragmentContainer = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int hellomoon_pauseButton = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int hellomoon_playButton = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int hellomoon_stopButton = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int menu_settings = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int videoView = 2131165188;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_hello_moon = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fragment_hello_moon = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int activity_menu_hello_moon = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int apollo_17_strollnexus = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int one_small_step = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int PigsInAPolka1943 = 2130968578;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int hello_world = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int hellomoon_audio = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int hellomoon_image_description = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int hellomoon_pause = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int hellomoon_play = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int hellomoon_stop = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int hellomoon_video = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int menu_settings = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
