#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("CriminalIntent.Resource", IsApplication=true)]

namespace CriminalIntent
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_horizontal_margin = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int activity_vertical_margin = 2130968577;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background_activated = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_launcher = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000e
			public const int button_new_crime = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int crime_camera_progressContainer = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int crime_camera_surfaceView = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int crime_camera_takePictureButton = 2131034124;
			
			// aapt resource value: 0x7f050009
			public const int crime_date_button = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int crime_details_textview = 2131034120;
			
			// aapt resource value: 0x7f050005
			public const int crime_imageButton = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int crime_imageView = 2131034116;
			
			// aapt resource value: 0x7f05000f
			public const int crime_list_item = 2131034127;
			
			// aapt resource value: 0x7f050012
			public const int crime_list_item_dateTextView = 2131034130;
			
			// aapt resource value: 0x7f050010
			public const int crime_list_item_solvedCheckBox = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int crime_list_item_titleTextView = 2131034129;
			
			// aapt resource value: 0x7f05000a
			public const int crime_solved_checkbox = 2131034122;
			
			// aapt resource value: 0x7f050007
			public const int crime_title_edittext = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int crime_title_textview = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int dialog_date_picker = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int dialog_time_picker = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int fragmentContainer = 2131034113;
			
			// aapt resource value: 0x7f050013
			public const int menu_item_delete_crime = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int menu_item_new_crime = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int menu_item_show_subtitle = 2131034133;
			
			// aapt resource value: 0x7f050000
			public const int viewPager = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_fragment = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dialog_date = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialog_time = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int fragment_crime = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int fragment_crime_camera = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int fragment_crimelist = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int list_item_crime = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int crime_list_item_context = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int fragment_crime_list = 2131230721;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int crime_details_text = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int crime_solved_text = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int crime_title = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int crime_title_hint = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int crime_title_text = 2131099653;
			
			// aapt resource value: 0x7f060009
			public const int crimes_title = 2131099657;
			
			// aapt resource value: 0x7f06000d
			public const int date_or_time_alert_date = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int date_or_time_alert_time = 2131099662;
			
			// aapt resource value: 0x7f06000c
			public const int date_or_time_alert_title = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int date_picker_title = 2131099658;
			
			// aapt resource value: 0x7f060013
			public const int delete_crime = 2131099667;
			
			// aapt resource value: 0x7f060011
			public const int hide_subtitle = 2131099665;
			
			// aapt resource value: 0x7f060015
			public const int list_empty_button_text = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int list_empty_text = 2131099668;
			
			// aapt resource value: 0x7f060001
			public const int menu_settings = 2131099649;
			
			// aapt resource value: 0x7f06000f
			public const int new_crime = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int show_subtitle = 2131099664;
			
			// aapt resource value: 0x7f060012
			public const int subtitle = 2131099666;
			
			// aapt resource value: 0x7f060016
			public const int take = 2131099670;
			
			// aapt resource value: 0x7f06000b
			public const int time_picker_title = 2131099659;
			
			// aapt resource value: 0x7f060002
			public const int title_activity_crime = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int title_activity_crimes = 2131099651;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int AppBaseTheme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int AppTheme = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
